version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./db/mongo:/data/db
    networks:
      - network
  app:
    build: .
    volumes:
      - .:/usr/src/
    networks:
      - network
    depends_on:
      - mongo
    command:
      npm start
      
networks:
  network:
    driver: bridge